export const projectsData = [
  {
    id: 1,
    title: "Ecommerce App –  Fresh Cart (Angular)",
    description: `Fresh Cart is a modern e-commerce web application that features user authentication, product browsing, shopping cart management, and a responsive design to provide a smooth and user-friendly online shopping experience.`,
    imageUrl: "/projects/freshcart.png",
    liveUrl:
      "https://fresh-cart-gs149jux1-mohamedsa3eed013-8953s-projects.vercel.app/#/signin",
    repoUrl: "https://github.com/muhhammedSa3eed/FreshCart",
    tech: ["HTML", "CSS", "Tailwind", "JavaScript", "Angular", "TypeScript"],
  },
  {
    id: 2,
    title: "Smart Health",
    description: `Smart Health is a fitness and wellness web platform that offers structured workout programs, health articles, and a calorie calculator, all within a clean, responsive interface to help users manage their health and fitness goals easily.`,
    imageUrl: "/projects/smartHealth.png",
    liveUrl: "https://smart-health-three.vercel.app/home",
    repoUrl: "https://github.com/muhhammedSa3eed/Smart-Health",
    tech: ["HTML", "CSS", "Tailwind", "JavaScript", "Angular", "TypeScript"],
  },

  {
    id: 3,
    title: "Flowmeter - [Under Development]",
    description: `Flowmeter Dashboard is a responsive web platform that offers real-time flowmeter monitoring, interactive charts, alerting, and device controls, all within a clean, responsive interface to help operators monitor and manage flow metrics efficiently.`,
    imageUrl: "/projects/flowmeter.png",
    liveUrl: "#None",
    repoUrl: "#None",
    tech: [
      "HTML",
      "CSS",
      "Tailwind",
      "JavaScript",
      "React JS",
      "Next JS",
      "TypeScript",
    ],
    isComingSoon: true,
  },
  {
    id: 4,
    title: "Quizzy",
    description: `Quizzy is an interactive online quiz web application that lets users test their knowledge through multiple‑choice quizzes across various topics and difficulty levels. It provides a clean and engaging interface where users can start quizzes, answer questions, and track their progress, making it suitable for learning, practice, and fun challenges.`,
    imageUrl: "/projects/quizzy.png",
    liveUrl: "https://quizzy-khaki.vercel.app/",
    repoUrl: "https://github.com/muhhammedSa3eed/quizzy",
    tech: [
      "HTML",
      "CSS",
      "Tailwind",
      "JavaScript",
      "React JS",
      "Next JS",
      "TypeScript",
      "Superbase",
    ],
    isComingSoon: false,
  },
  {
    id: 5,
    title: "Dashboard - [Under Development]",
    description:
      "A modern dashboard template built with React and Vite, featuring responsive design and customizable components for data visualization and management.",
    imageUrl: "/projects/job.jpeg",
    liveUrl: "#",
    repoUrl: "",
    tech: ["React", "Vite"],
    isComingSoon: true,
  },
  {
    id: 5,
    title: "Apple Clone",
    description:
      "Apple Clone is a modern e-commerce web application that replicates the look and feel of the official Apple store. It allows users to browse products, explore detailed product pages, and interact with a clean, responsive interface, providing a seamless and visually appealing shopping experience.",
    imageUrl: "/projects/apple.png",
    liveUrl: "https://alinour.me/",
    repoUrl: "https://github.com/alin00r/E-Shop-Website",
    tech: ["HTML", "CSS", "JavaScript"],
    isComingSoon: true,
  },
];
